[package]
name = "rusty_lua_dec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
modular-bitfield = "0.11.2"
nom = "7.1.3"
